export interface PresetMeal {
  name: string;
  time: string;
  calories: number;
  proteinG: number;
  carbsG: number;
  fatsG: number;
  ingredients?: Array<{
    name: string;
    amount: string;
    unit?: string;
  }>;
  instructions?: string;
}

export interface PresetMealPlanDay {
  meals: PresetMeal[];
}

export interface PresetMealPlan {
  id: string;
  name: string;
  description: string;
  goal: 'Fat Loss' | 'Muscle Gain' | 'Strength & Conditioning' | 'Maintenance';
  plan: {
    Mon: PresetMealPlanDay;
    Tue: PresetMealPlanDay;
    Wed: PresetMealPlanDay;
    Thu: PresetMealPlanDay;
    Fri: PresetMealPlanDay;
    Sat: PresetMealPlanDay;
    Sun: PresetMealPlanDay;
  };
  totalCalories: number;
  totalProtein: number;
  totalCarbs: number;
  totalFats: number;
}

export const PRESET_MEAL_PLANS: PresetMealPlan[] = [
  {
    id: 'fat-loss-balanced',
    name: 'Balanced Fat Loss',
    description: 'A well-rounded meal plan for sustainable fat loss with balanced macros',
    goal: 'Fat Loss',
    plan: {
      Mon: {
        meals: [
          {
            name: 'Greek Yogurt with Berries',
            time: '08:00',
            calories: 250,
            proteinG: 20,
            carbsG: 30,
            fatsG: 5,
            ingredients: [
              { name: 'Greek yogurt (non-fat)', amount: '200', unit: 'g' },
              { name: 'Mixed berries (strawberries, blueberries)', amount: '100', unit: 'g' },
              { name: 'Honey', amount: '1', unit: 'tbsp' },
            ],
            instructions: 'Mix Greek yogurt with fresh berries. Drizzle with honey. Serve chilled.',
          },
          {
            name: 'Grilled Chicken Salad',
            time: '12:30',
            calories: 400,
            proteinG: 35,
            carbsG: 25,
            fatsG: 15,
            ingredients: [
              { name: 'Chicken breast (skinless)', amount: '150', unit: 'g' },
              { name: 'Mixed greens (lettuce, spinach)', amount: '100', unit: 'g' },
              { name: 'Cherry tomatoes', amount: '80', unit: 'g' },
              { name: 'Cucumber', amount: '50', unit: 'g' },
              { name: 'Olive oil', amount: '1', unit: 'tbsp' },
              { name: 'Lemon juice', amount: '1', unit: 'tbsp' },
            ],
            instructions: 'Grill chicken breast until cooked through (165°F). Slice and serve over mixed greens with tomatoes and cucumber. Dress with olive oil and lemon juice.',
          },
          {
            name: 'Apple with Almonds',
            time: '15:00',
            calories: 200,
            proteinG: 5,
            carbsG: 20,
            fatsG: 12,
            ingredients: [
              { name: 'Apple (medium)', amount: '1', unit: 'whole' },
              { name: 'Almonds (raw)', amount: '20', unit: 'g' },
            ],
            instructions: 'Slice apple and enjoy with a handful of raw almonds.',
          },
          {
            name: 'Salmon with Vegetables',
            time: '19:00',
            calories: 450,
            proteinG: 40,
            carbsG: 20,
            fatsG: 20,
            ingredients: [
              { name: 'Salmon fillet', amount: '150', unit: 'g' },
              { name: 'Broccoli', amount: '150', unit: 'g' },
              { name: 'Asparagus', amount: '100', unit: 'g' },
              { name: 'Olive oil', amount: '1', unit: 'tbsp' },
              { name: 'Garlic', amount: '2', unit: 'cloves' },
              { name: 'Lemon', amount: '0.5', unit: 'whole' },
            ],
            instructions: 'Season salmon with salt, pepper, and lemon. Bake at 400°F for 12-15 minutes. Steam or roast broccoli and asparagus with garlic and olive oil until tender.',
          },
        ],
      },
      Tue: {
        meals: [
          {
            name: 'Oatmeal with Protein',
            time: '08:00',
            calories: 300,
            proteinG: 25,
            carbsG: 45,
            fatsG: 8,
            ingredients: [
              { name: 'Rolled oats (dry)', amount: '50', unit: 'g' },
              { name: 'Whey protein powder', amount: '30', unit: 'g' },
              { name: 'Almond milk (unsweetened)', amount: '200', unit: 'ml' },
              { name: 'Banana (sliced)', amount: '0.5', unit: 'medium' },
            ],
            instructions: 'Cook oats with almond milk. Stir in protein powder after cooking. Top with banana slices.',
          },
          {
            name: 'Turkey Wrap',
            time: '12:30',
            calories: 380,
            proteinG: 30,
            carbsG: 35,
            fatsG: 12,
            ingredients: [
              { name: 'Whole wheat tortilla', amount: '1', unit: 'large' },
              { name: 'Turkey breast (sliced)', amount: '100', unit: 'g' },
              { name: 'Lettuce', amount: '30', unit: 'g' },
              { name: 'Tomato', amount: '50', unit: 'g' },
              { name: 'Avocado', amount: '30', unit: 'g' },
            ],
            instructions: 'Layer turkey, lettuce, tomato, and avocado on tortilla. Roll tightly and slice in half.',
          },
          {
            name: 'Protein Shake',
            time: '15:00',
            calories: 180,
            proteinG: 25,
            carbsG: 10,
            fatsG: 3,
            ingredients: [
              { name: 'Whey protein powder', amount: '30', unit: 'g' },
              { name: 'Water', amount: '250', unit: 'ml' },
              { name: 'Ice cubes', amount: '4-5', unit: 'pieces' },
            ],
            instructions: 'Blend protein powder with water and ice until smooth.',
          },
          {
            name: 'Lean Beef with Sweet Potato',
            time: '19:00',
            calories: 420,
            proteinG: 35,
            carbsG: 30,
            fatsG: 15,
            ingredients: [
              { name: 'Lean ground beef (93/7)', amount: '120', unit: 'g' },
              { name: 'Sweet potato (medium)', amount: '200', unit: 'g' },
              { name: 'Green beans', amount: '100', unit: 'g' },
              { name: 'Olive oil', amount: '0.5', unit: 'tbsp' },
            ],
            instructions: 'Cook ground beef in a pan. Bake sweet potato at 400°F for 45 minutes. Steam green beans. Serve together.',
          },
        ],
      },
      Wed: {
        meals: [
          {
            name: 'Scrambled Eggs with Toast',
            time: '08:00',
            calories: 280,
            proteinG: 20,
            carbsG: 25,
            fatsG: 12,
            ingredients: [
              { name: 'Eggs (whole)', amount: '2', unit: 'large' },
              { name: 'Whole wheat bread', amount: '1', unit: 'slice' },
              { name: 'Butter', amount: '5', unit: 'g' },
              { name: 'Spinach', amount: '30', unit: 'g' },
            ],
            instructions: 'Scramble eggs with spinach. Toast bread and spread with butter. Serve together.',
          },
          {
            name: 'Tuna Salad',
            time: '12:30',
            calories: 350,
            proteinG: 30,
            carbsG: 20,
            fatsG: 15,
            ingredients: [
              { name: 'Canned tuna (in water)', amount: '120', unit: 'g' },
              { name: 'Greek yogurt', amount: '50', unit: 'g' },
              { name: 'Celery (diced)', amount: '30', unit: 'g' },
              { name: 'Red onion (diced)', amount: '20', unit: 'g' },
              { name: 'Mixed greens', amount: '80', unit: 'g' },
            ],
            instructions: 'Mix tuna with Greek yogurt, celery, and onion. Serve over mixed greens.',
          },
          {
            name: 'Greek Yogurt',
            time: '15:00',
            calories: 150,
            proteinG: 15,
            carbsG: 15,
            fatsG: 3,
            ingredients: [
              { name: 'Greek yogurt (non-fat)', amount: '150', unit: 'g' },
            ],
            instructions: 'Enjoy plain or with a dash of cinnamon.',
          },
          {
            name: 'Chicken Stir Fry',
            time: '19:00',
            calories: 400,
            proteinG: 35,
            carbsG: 30,
            fatsG: 12,
            ingredients: [
              { name: 'Chicken breast (diced)', amount: '150', unit: 'g' },
              { name: 'Broccoli', amount: '100', unit: 'g' },
              { name: 'Bell peppers', amount: '80', unit: 'g' },
              { name: 'Carrots', amount: '50', unit: 'g' },
              { name: 'Soy sauce (low sodium)', amount: '1', unit: 'tbsp' },
              { name: 'Olive oil', amount: '1', unit: 'tbsp' },
            ],
            instructions: 'Stir-fry chicken until cooked. Add vegetables and cook until tender. Season with soy sauce.',
          },
        ],
      },
      Thu: {
        meals: [
          {
            name: 'Protein Pancakes',
            time: '08:00',
            calories: 320,
            proteinG: 30,
            carbsG: 40,
            fatsG: 8,
            ingredients: [
              { name: 'Protein powder', amount: '30', unit: 'g' },
              { name: 'Oat flour', amount: '40', unit: 'g' },
              { name: 'Egg whites', amount: '100', unit: 'ml' },
              { name: 'Banana (mashed)', amount: '0.5', unit: 'medium' },
              { name: 'Baking powder', amount: '0.5', unit: 'tsp' },
            ],
            instructions: 'Mix all ingredients. Cook pancakes on medium heat for 2-3 minutes per side.',
          },
          {
            name: 'Chicken Quinoa Bowl',
            time: '12:30',
            calories: 420,
            proteinG: 35,
            carbsG: 45,
            fatsG: 10,
            ingredients: [
              { name: 'Chicken breast (grilled)', amount: '150', unit: 'g' },
              { name: 'Quinoa (cooked)', amount: '100', unit: 'g' },
              { name: 'Black beans', amount: '60', unit: 'g' },
              { name: 'Corn', amount: '50', unit: 'g' },
              { name: 'Avocado', amount: '30', unit: 'g' },
            ],
            instructions: 'Layer quinoa, black beans, corn, and grilled chicken. Top with sliced avocado.',
          },
          {
            name: 'Mixed Nuts',
            time: '15:00',
            calories: 200,
            proteinG: 6,
            carbsG: 8,
            fatsG: 16,
            ingredients: [
              { name: 'Almonds', amount: '10', unit: 'g' },
              { name: 'Walnuts', amount: '10', unit: 'g' },
              { name: 'Cashews', amount: '10', unit: 'g' },
            ],
            instructions: 'Mix and enjoy as a snack.',
          },
          {
            name: 'Baked Cod with Vegetables',
            time: '19:00',
            calories: 380,
            proteinG: 35,
            carbsG: 25,
            fatsG: 15,
            ingredients: [
              { name: 'Cod fillet', amount: '150', unit: 'g' },
              { name: 'Zucchini', amount: '100', unit: 'g' },
              { name: 'Bell peppers', amount: '80', unit: 'g' },
              { name: 'Olive oil', amount: '1', unit: 'tbsp' },
              { name: 'Herbs (dried)', amount: '1', unit: 'tsp' },
            ],
            instructions: 'Season cod and vegetables. Bake at 375°F for 20 minutes until fish flakes easily.',
          },
        ],
      },
      Fri: {
        meals: [
          {
            name: 'Smoothie Bowl',
            time: '08:00',
            calories: 280,
            proteinG: 20,
            carbsG: 35,
            fatsG: 8,
            ingredients: [
              { name: 'Frozen berries', amount: '100', unit: 'g' },
              { name: 'Greek yogurt', amount: '100', unit: 'g' },
              { name: 'Banana (frozen)', amount: '0.5', unit: 'medium' },
              { name: 'Granola', amount: '20', unit: 'g' },
            ],
            instructions: 'Blend frozen berries, yogurt, and banana until smooth. Pour into bowl and top with granola.',
          },
          {
            name: 'Grilled Chicken Breast',
            time: '12:30',
            calories: 350,
            proteinG: 40,
            carbsG: 15,
            fatsG: 12,
            ingredients: [
              { name: 'Chicken breast (skinless)', amount: '150', unit: 'g' },
              { name: 'Brown rice (cooked)', amount: '80', unit: 'g' },
              { name: 'Steamed vegetables', amount: '100', unit: 'g' },
              { name: 'Olive oil', amount: '0.5', unit: 'tbsp' },
            ],
            instructions: 'Grill chicken until internal temperature reaches 165°F. Serve with brown rice and steamed vegetables.',
          },
          {
            name: 'Rice Cakes with Peanut Butter',
            time: '15:00',
            calories: 180,
            proteinG: 8,
            carbsG: 20,
            fatsG: 8,
            ingredients: [
              { name: 'Rice cakes', amount: '2', unit: 'pieces' },
              { name: 'Peanut butter (natural)', amount: '15', unit: 'g' },
            ],
            instructions: 'Spread peanut butter on rice cakes.',
          },
          {
            name: 'Turkey Meatballs with Pasta',
            time: '19:00',
            calories: 450,
            proteinG: 35,
            carbsG: 40,
            fatsG: 15,
            ingredients: [
              { name: 'Ground turkey (93/7)', amount: '120', unit: 'g' },
              { name: 'Whole wheat pasta (cooked)', amount: '80', unit: 'g' },
              { name: 'Marinara sauce', amount: '100', unit: 'g' },
              { name: 'Parmesan cheese', amount: '10', unit: 'g' },
            ],
            instructions: 'Form turkey into meatballs and bake at 375°F for 20 minutes. Serve over pasta with marinara sauce and parmesan.',
          },
        ],
      },
      Sat: {
        meals: [
          {
            name: 'Avocado Toast with Eggs',
            time: '08:00',
            calories: 320,
            proteinG: 18,
            carbsG: 30,
            fatsG: 15,
            ingredients: [
              { name: 'Whole wheat bread', amount: '2', unit: 'slices' },
              { name: 'Avocado', amount: '50', unit: 'g' },
              { name: 'Eggs (poached)', amount: '2', unit: 'large' },
              { name: 'Salt and pepper', amount: 'to taste', unit: '' },
            ],
            instructions: 'Toast bread. Mash avocado and spread on toast. Top with poached eggs. Season with salt and pepper.',
          },
          {
            name: 'Salmon Salad',
            time: '12:30',
            calories: 400,
            proteinG: 30,
            carbsG: 20,
            fatsG: 20,
            ingredients: [
              { name: 'Salmon (cooked)', amount: '120', unit: 'g' },
              { name: 'Mixed greens', amount: '100', unit: 'g' },
              { name: 'Cucumber', amount: '50', unit: 'g' },
              { name: 'Olive oil', amount: '1', unit: 'tbsp' },
              { name: 'Lemon juice', amount: '1', unit: 'tbsp' },
            ],
            instructions: 'Flake cooked salmon over mixed greens and cucumber. Dress with olive oil and lemon juice.',
          },
          {
            name: 'Protein Bar',
            time: '15:00',
            calories: 200,
            proteinG: 20,
            carbsG: 20,
            fatsG: 5,
            ingredients: [
              { name: 'Protein bar', amount: '1', unit: 'bar (50g)' },
            ],
            instructions: 'Enjoy as a convenient snack.',
          },
          {
            name: 'Lean Steak with Vegetables',
            time: '19:00',
            calories: 420,
            proteinG: 40,
            carbsG: 15,
            fatsG: 18,
            ingredients: [
              { name: 'Sirloin steak (lean)', amount: '120', unit: 'g' },
              { name: 'Asparagus', amount: '100', unit: 'g' },
              { name: 'Mushrooms', amount: '80', unit: 'g' },
              { name: 'Olive oil', amount: '1', unit: 'tbsp' },
            ],
            instructions: 'Grill or pan-sear steak to desired doneness. Roast asparagus and mushrooms with olive oil at 400°F for 15 minutes.',
          },
        ],
      },
      Sun: {
        meals: [
          {
            name: 'Protein Waffles',
            time: '08:00',
            calories: 300,
            proteinG: 25,
            carbsG: 35,
            fatsG: 8,
            ingredients: [
              { name: 'Protein powder', amount: '30', unit: 'g' },
              { name: 'Oat flour', amount: '40', unit: 'g' },
              { name: 'Egg whites', amount: '100', unit: 'ml' },
              { name: 'Baking powder', amount: '0.5', unit: 'tsp' },
            ],
            instructions: 'Mix ingredients and cook in waffle iron until golden brown.',
          },
          {
            name: 'Chicken Caesar Salad',
            time: '12:30',
            calories: 380,
            proteinG: 30,
            carbsG: 25,
            fatsG: 18,
            ingredients: [
              { name: 'Chicken breast (grilled)', amount: '120', unit: 'g' },
              { name: 'Romaine lettuce', amount: '100', unit: 'g' },
              { name: 'Caesar dressing (light)', amount: '2', unit: 'tbsp' },
              { name: 'Parmesan cheese', amount: '10', unit: 'g' },
            ],
            instructions: 'Toss romaine with dressing. Top with grilled chicken and parmesan cheese.',
          },
          {
            name: 'Cottage Cheese with Fruit',
            time: '15:00',
            calories: 180,
            proteinG: 20,
            carbsG: 15,
            fatsG: 5,
            ingredients: [
              { name: 'Cottage cheese (low-fat)', amount: '150', unit: 'g' },
              { name: 'Mixed berries', amount: '50', unit: 'g' },
            ],
            instructions: 'Top cottage cheese with fresh berries.',
          },
          {
            name: 'Baked Chicken with Rice',
            time: '19:00',
            calories: 440,
            proteinG: 40,
            carbsG: 40,
            fatsG: 12,
            ingredients: [
              { name: 'Chicken breast (skinless)', amount: '150', unit: 'g' },
              { name: 'Brown rice (cooked)', amount: '100', unit: 'g' },
              { name: 'Steamed broccoli', amount: '100', unit: 'g' },
              { name: 'Olive oil', amount: '0.5', unit: 'tbsp' },
            ],
            instructions: 'Bake chicken at 375°F for 25 minutes. Serve with brown rice and steamed broccoli.',
          },
        ],
      },
    },
    totalCalories: 1300,
    totalProtein: 120,
    totalCarbs: 130,
    totalFats: 45,
  },
  {
    id: 'muscle-gain-high-protein',
    name: 'High Protein Muscle Gain',
    description: 'High-calorie, high-protein plan designed for muscle building',
    goal: 'Muscle Gain',
    plan: {
      Mon: {
        meals: [
          {
            name: 'Protein Oatmeal with Banana',
            time: '08:00',
            calories: 450,
            proteinG: 30,
            carbsG: 60,
            fatsG: 10,
            ingredients: [
              { name: 'Rolled oats (dry)', amount: '80', unit: 'g' },
              { name: 'Whey protein powder', amount: '40', unit: 'g' },
              { name: 'Banana (large)', amount: '1', unit: 'whole' },
              { name: 'Almond milk', amount: '200', unit: 'ml' },
              { name: 'Peanut butter', amount: '15', unit: 'g' },
            ],
            instructions: 'Cook oats with almond milk. Stir in protein powder. Top with sliced banana and peanut butter.',
          },
          {
            name: 'Chicken and Rice',
            time: '12:30',
            calories: 600,
            proteinG: 50,
            carbsG: 70,
            fatsG: 15,
            ingredients: [
              { name: 'Chicken breast', amount: '200', unit: 'g' },
              { name: 'White rice (cooked)', amount: '150', unit: 'g' },
              { name: 'Broccoli', amount: '150', unit: 'g' },
              { name: 'Olive oil', amount: '1', unit: 'tbsp' },
            ],
            instructions: 'Grill chicken. Serve with rice and steamed broccoli drizzled with olive oil.',
          },
          {
            name: 'Protein Shake',
            time: '15:00',
            calories: 250,
            proteinG: 30,
            carbsG: 25,
            fatsG: 5,
            ingredients: [
              { name: 'Whey protein powder', amount: '40', unit: 'g' },
              { name: 'Milk (2%)', amount: '250', unit: 'ml' },
              { name: 'Banana', amount: '0.5', unit: 'medium' },
            ],
            instructions: 'Blend all ingredients until smooth.',
          },
          {
            name: 'Beef with Potatoes',
            time: '19:00',
            calories: 650,
            proteinG: 55,
            carbsG: 60,
            fatsG: 20,
            ingredients: [
              { name: 'Lean beef steak', amount: '180', unit: 'g' },
              { name: 'Potatoes (roasted)', amount: '200', unit: 'g' },
              { name: 'Green beans', amount: '100', unit: 'g' },
              { name: 'Butter', amount: '10', unit: 'g' },
            ],
            instructions: 'Grill or pan-sear steak. Roast potatoes at 400°F for 45 minutes. Steam green beans. Serve together.',
          },
          {
            name: 'Casein Protein',
            time: '21:30',
            calories: 200,
            proteinG: 25,
            carbsG: 5,
            fatsG: 3,
            ingredients: [
              { name: 'Casein protein powder', amount: '35', unit: 'g' },
              { name: 'Water', amount: '250', unit: 'ml' },
            ],
            instructions: 'Mix casein protein with water. Drink before bed for slow-release protein.',
          },
        ],
      },
      Tue: {
        meals: [
          {
            name: 'Egg Scramble with Toast',
            time: '08:00',
            calories: 500,
            proteinG: 35,
            carbsG: 55,
            fatsG: 15,
            ingredients: [
              { name: 'Eggs (whole)', amount: '3', unit: 'large' },
              { name: 'Whole wheat bread', amount: '2', unit: 'slices' },
              { name: 'Cheese (cheddar)', amount: '30', unit: 'g' },
              { name: 'Butter', amount: '10', unit: 'g' },
            ],
            instructions: 'Scramble eggs with cheese. Toast bread and butter. Serve together.',
          },
          {
            name: 'Turkey and Pasta',
            time: '12:30',
            calories: 620,
            proteinG: 45,
            carbsG: 75,
            fatsG: 18,
            ingredients: [
              { name: 'Ground turkey', amount: '150', unit: 'g' },
              { name: 'Whole wheat pasta (cooked)', amount: '120', unit: 'g' },
              { name: 'Marinara sauce', amount: '150', unit: 'g' },
              { name: 'Parmesan cheese', amount: '15', unit: 'g' },
            ],
            instructions: 'Cook ground turkey. Mix with pasta and marinara sauce. Top with parmesan.',
          },
          {
            name: 'Greek Yogurt with Granola',
            time: '15:00',
            calories: 300,
            proteinG: 20,
            carbsG: 40,
            fatsG: 8,
            ingredients: [
              { name: 'Greek yogurt (full-fat)', amount: '200', unit: 'g' },
              { name: 'Granola', amount: '40', unit: 'g' },
            ],
            instructions: 'Top Greek yogurt with granola.',
          },
          {
            name: 'Salmon with Sweet Potato',
            time: '19:00',
            calories: 600,
            proteinG: 50,
            carbsG: 65,
            fatsG: 20,
            ingredients: [
              { name: 'Salmon fillet', amount: '180', unit: 'g' },
              { name: 'Sweet potato (large)', amount: '250', unit: 'g' },
              { name: 'Asparagus', amount: '100', unit: 'g' },
              { name: 'Olive oil', amount: '1', unit: 'tbsp' },
            ],
            instructions: 'Bake salmon at 400°F for 15 minutes. Bake sweet potato at 400°F for 45 minutes. Roast asparagus.',
          },
          {
            name: 'Cottage Cheese',
            time: '21:30',
            calories: 180,
            proteinG: 25,
            carbsG: 8,
            fatsG: 2,
            ingredients: [
              { name: 'Cottage cheese (low-fat)', amount: '200', unit: 'g' },
            ],
            instructions: 'Enjoy plain or with a dash of cinnamon.',
          },
        ],
      },
      Wed: {
        meals: [
          {
            name: 'Protein Pancakes',
            time: '08:00',
            calories: 480,
            proteinG: 35,
            carbsG: 60,
            fatsG: 12,
            ingredients: [
              { name: 'Protein powder', amount: '40', unit: 'g' },
              { name: 'Oat flour', amount: '60', unit: 'g' },
              { name: 'Eggs (whole)', amount: '2', unit: 'large' },
              { name: 'Banana', amount: '0.5', unit: 'medium' },
              { name: 'Maple syrup', amount: '1', unit: 'tbsp' },
            ],
            instructions: 'Mix ingredients and cook pancakes. Serve with maple syrup.',
          },
          {
            name: 'Chicken Quinoa Bowl',
            time: '12:30',
            calories: 580,
            proteinG: 50,
            carbsG: 70,
            fatsG: 15,
            ingredients: [
              { name: 'Chicken breast', amount: '180', unit: 'g' },
              { name: 'Quinoa (cooked)', amount: '150', unit: 'g' },
              { name: 'Black beans', amount: '100', unit: 'g' },
              { name: 'Avocado', amount: '50', unit: 'g' },
            ],
            instructions: 'Layer quinoa, black beans, grilled chicken, and avocado.',
          },
          {
            name: 'Protein Bar',
            time: '15:00',
            calories: 280,
            proteinG: 25,
            carbsG: 30,
            fatsG: 8,
            ingredients: [
              { name: 'Protein bar', amount: '1', unit: 'bar (60g)' },
            ],
            instructions: 'Enjoy as a convenient snack.',
          },
          {
            name: 'Lean Beef with Rice',
            time: '19:00',
            calories: 640,
            proteinG: 55,
            carbsG: 65,
            fatsG: 18,
            ingredients: [
              { name: 'Lean ground beef (93/7)', amount: '180', unit: 'g' },
              { name: 'White rice (cooked)', amount: '150', unit: 'g' },
              { name: 'Mixed vegetables', amount: '150', unit: 'g' },
              { name: 'Olive oil', amount: '1', unit: 'tbsp' },
            ],
            instructions: 'Cook ground beef. Serve with rice and sautéed vegetables.',
          },
          {
            name: 'Casein Shake',
            time: '21:30',
            calories: 220,
            proteinG: 30,
            carbsG: 10,
            fatsG: 4,
            ingredients: [
              { name: 'Casein protein powder', amount: '40', unit: 'g' },
              { name: 'Milk (2%)', amount: '200', unit: 'ml' },
            ],
            instructions: 'Mix casein with milk. Drink before bed.',
          },
        ],
      },
      Thu: {
        meals: [
          {
            name: 'Smoothie with Protein',
            time: '08:00',
            calories: 450,
            proteinG: 30,
            carbsG: 55,
            fatsG: 10,
            ingredients: [
              { name: 'Whey protein powder', amount: '40', unit: 'g' },
              { name: 'Frozen berries', amount: '100', unit: 'g' },
              { name: 'Banana', amount: '1', unit: 'medium' },
              { name: 'Greek yogurt', amount: '100', unit: 'g' },
              { name: 'Milk', amount: '200', unit: 'ml' },
            ],
            instructions: 'Blend all ingredients until smooth.',
          },
          {
            name: 'Tuna Pasta',
            time: '12:30',
            calories: 600,
            proteinG: 45,
            carbsG: 75,
            fatsG: 15,
            ingredients: [
              { name: 'Canned tuna (in olive oil)', amount: '150', unit: 'g' },
              { name: 'Whole wheat pasta (cooked)', amount: '120', unit: 'g' },
              { name: 'Olive oil', amount: '1', unit: 'tbsp' },
              { name: 'Lemon juice', amount: '1', unit: 'tbsp' },
            ],
            instructions: 'Mix tuna with pasta. Drizzle with olive oil and lemon juice.',
          },
          {
            name: 'Mixed Nuts and Dried Fruit',
            time: '15:00',
            calories: 320,
            proteinG: 10,
            carbsG: 35,
            fatsG: 18,
            ingredients: [
              { name: 'Mixed nuts', amount: '30', unit: 'g' },
              { name: 'Dried apricots', amount: '40', unit: 'g' },
            ],
            instructions: 'Mix and enjoy as a snack.',
          },
          {
            name: 'Chicken with Potatoes',
            time: '19:00',
            calories: 620,
            proteinG: 50,
            carbsG: 70,
            fatsG: 15,
            ingredients: [
              { name: 'Chicken breast', amount: '200', unit: 'g' },
              { name: 'Potatoes (roasted)', amount: '250', unit: 'g' },
              { name: 'Green beans', amount: '100', unit: 'g' },
              { name: 'Butter', amount: '10', unit: 'g' },
            ],
            instructions: 'Grill chicken. Roast potatoes. Steam green beans with butter.',
          },
          {
            name: 'Greek Yogurt',
            time: '21:30',
            calories: 210,
            proteinG: 20,
            carbsG: 15,
            fatsG: 5,
            ingredients: [
              { name: 'Greek yogurt (full-fat)', amount: '200', unit: 'g' },
            ],
            instructions: 'Enjoy plain or with a drizzle of honey.',
          },
        ],
      },
      Fri: {
        meals: [
          {
            name: 'Avocado Toast with Eggs',
            time: '08:00',
            calories: 480,
            proteinG: 28,
            carbsG: 50,
            fatsG: 18,
            ingredients: [
              { name: 'Whole wheat bread', amount: '2', unit: 'slices' },
              { name: 'Avocado', amount: '80', unit: 'g' },
              { name: 'Eggs (fried)', amount: '2', unit: 'large' },
              { name: 'Feta cheese', amount: '30', unit: 'g' },
            ],
            instructions: 'Toast bread. Mash avocado and spread on toast. Top with fried eggs and feta cheese.',
          },
          {
            name: 'Salmon and Rice',
            time: '12:30',
            calories: 580,
            proteinG: 50,
            carbsG: 65,
            fatsG: 20,
            ingredients: [
              { name: 'Salmon fillet', amount: '180', unit: 'g' },
              { name: 'White rice (cooked)', amount: '150', unit: 'g' },
              { name: 'Broccoli', amount: '150', unit: 'g' },
              { name: 'Olive oil', amount: '1', unit: 'tbsp' },
            ],
            instructions: 'Bake salmon at 400°F for 15 minutes. Serve with rice and steamed broccoli.',
          },
          {
            name: 'Protein Shake',
            time: '15:00',
            calories: 250,
            proteinG: 30,
            carbsG: 25,
            fatsG: 5,
            ingredients: [
              { name: 'Whey protein powder', amount: '40', unit: 'g' },
              { name: 'Milk', amount: '250', unit: 'ml' },
              { name: 'Banana', amount: '0.5', unit: 'medium' },
            ],
            instructions: 'Blend all ingredients until smooth.',
          },
          {
            name: 'Turkey Meatballs with Pasta',
            time: '19:00',
            calories: 640,
            proteinG: 48,
            carbsG: 75,
            fatsG: 18,
            ingredients: [
              { name: 'Ground turkey', amount: '180', unit: 'g' },
              { name: 'Whole wheat pasta (cooked)', amount: '120', unit: 'g' },
              { name: 'Marinara sauce', amount: '150', unit: 'g' },
              { name: 'Mozzarella cheese', amount: '30', unit: 'g' },
            ],
            instructions: 'Form turkey into meatballs and bake. Serve over pasta with marinara and mozzarella.',
          },
          {
            name: 'Casein Protein',
            time: '21:30',
            calories: 200,
            proteinG: 25,
            carbsG: 5,
            fatsG: 3,
            ingredients: [
              { name: 'Casein protein powder', amount: '35', unit: 'g' },
              { name: 'Water', amount: '250', unit: 'ml' },
            ],
            instructions: 'Mix casein with water. Drink before bed.',
          },
        ],
      },
      Sat: {
        meals: [
          {
            name: 'Breakfast Burrito',
            time: '08:00',
            calories: 520,
            proteinG: 35,
            carbsG: 60,
            fatsG: 15,
            ingredients: [
              { name: 'Whole wheat tortilla (large)', amount: '1', unit: 'whole' },
              { name: 'Eggs (scrambled)', amount: '3', unit: 'large' },
              { name: 'Black beans', amount: '80', unit: 'g' },
              { name: 'Cheese (cheddar)', amount: '30', unit: 'g' },
              { name: 'Salsa', amount: '30', unit: 'g' },
            ],
            instructions: 'Scramble eggs. Warm tortilla. Fill with eggs, beans, cheese, and salsa. Roll tightly.',
          },
          {
            name: 'Steak with Sweet Potato',
            time: '12:30',
            calories: 650,
            proteinG: 55,
            carbsG: 70,
            fatsG: 20,
            ingredients: [
              { name: 'Sirloin steak', amount: '200', unit: 'g' },
              { name: 'Sweet potato (large)', amount: '300', unit: 'g' },
              { name: 'Asparagus', amount: '150', unit: 'g' },
              { name: 'Butter', amount: '10', unit: 'g' },
            ],
            instructions: 'Grill steak to desired doneness. Bake sweet potato at 400°F for 45 minutes. Roast asparagus with butter.',
          },
          {
            name: 'Trail Mix',
            time: '15:00',
            calories: 300,
            proteinG: 8,
            carbsG: 30,
            fatsG: 18,
            ingredients: [
              { name: 'Mixed nuts', amount: '30', unit: 'g' },
              { name: 'Dried cranberries', amount: '30', unit: 'g' },
              { name: 'Dark chocolate chips', amount: '15', unit: 'g' },
            ],
            instructions: 'Mix and enjoy as a snack.',
          },
          {
            name: 'Baked Cod with Rice',
            time: '19:00',
            calories: 580,
            proteinG: 50,
            carbsG: 65,
            fatsG: 15,
            ingredients: [
              { name: 'Cod fillet', amount: '200', unit: 'g' },
              { name: 'White rice (cooked)', amount: '150', unit: 'g' },
              { name: 'Mixed vegetables', amount: '150', unit: 'g' },
              { name: 'Lemon butter sauce', amount: '20', unit: 'g' },
            ],
            instructions: 'Bake cod at 375°F for 20 minutes. Serve with rice, vegetables, and lemon butter sauce.',
          },
          {
            name: 'Cottage Cheese',
            time: '21:30',
            calories: 200,
            proteinG: 25,
            carbsG: 10,
            fatsG: 2,
            ingredients: [
              { name: 'Cottage cheese (low-fat)', amount: '200', unit: 'g' },
            ],
            instructions: 'Enjoy plain or with a dash of cinnamon.',
          },
        ],
      },
      Sun: {
        meals: [
          {
            name: 'Protein Waffles',
            time: '08:00',
            calories: 480,
            proteinG: 32,
            carbsG: 60,
            fatsG: 12,
            ingredients: [
              { name: 'Protein powder', amount: '40', unit: 'g' },
              { name: 'Oat flour', amount: '60', unit: 'g' },
              { name: 'Eggs (whole)', amount: '2', unit: 'large' },
              { name: 'Maple syrup', amount: '1', unit: 'tbsp' },
            ],
            instructions: 'Mix ingredients and cook in waffle iron. Serve with maple syrup.',
          },
          {
            name: 'Chicken Caesar Wrap',
            time: '12:30',
            calories: 580,
            proteinG: 45,
            carbsG: 55,
            fatsG: 20,
            ingredients: [
              { name: 'Whole wheat tortilla (large)', amount: '1', unit: 'whole' },
              { name: 'Chicken breast (grilled)', amount: '150', unit: 'g' },
              { name: 'Romaine lettuce', amount: '50', unit: 'g' },
              { name: 'Caesar dressing', amount: '2', unit: 'tbsp' },
              { name: 'Parmesan cheese', amount: '15', unit: 'g' },
            ],
            instructions: 'Layer chicken, lettuce, dressing, and parmesan on tortilla. Roll tightly.',
          },
          {
            name: 'Protein Smoothie',
            time: '15:00',
            calories: 280,
            proteinG: 30,
            carbsG: 30,
            fatsG: 6,
            ingredients: [
              { name: 'Whey protein powder', amount: '40', unit: 'g' },
              { name: 'Frozen berries', amount: '80', unit: 'g' },
              { name: 'Greek yogurt', amount: '100', unit: 'g' },
              { name: 'Milk', amount: '200', unit: 'ml' },
            ],
            instructions: 'Blend all ingredients until smooth.',
          },
          {
            name: 'Lean Beef with Vegetables',
            time: '19:00',
            calories: 620,
            proteinG: 55,
            carbsG: 50,
            fatsG: 20,
            ingredients: [
              { name: 'Lean ground beef (93/7)', amount: '200', unit: 'g' },
              { name: 'Brown rice (cooked)', amount: '120', unit: 'g' },
              { name: 'Mixed vegetables (stir-fried)', amount: '200', unit: 'g' },
              { name: 'Olive oil', amount: '1', unit: 'tbsp' },
            ],
            instructions: 'Cook ground beef. Serve with rice and stir-fried vegetables.',
          },
          {
            name: 'Casein Shake',
            time: '21:30',
            calories: 220,
            proteinG: 30,
            carbsG: 8,
            fatsG: 4,
            ingredients: [
              { name: 'Casein protein powder', amount: '40', unit: 'g' },
              { name: 'Milk (2%)', amount: '200', unit: 'ml' },
            ],
            instructions: 'Mix casein with milk. Drink before bed.',
          },
        ],
      },
    },
    totalCalories: 2200,
    totalProtein: 180,
    totalCarbs: 240,
    totalFats: 65,
  },
];

export function getPresetMealPlansByGoal(goal?: string): PresetMealPlan[] {
  if (!goal) return PRESET_MEAL_PLANS;
  return PRESET_MEAL_PLANS.filter((plan) => plan.goal === goal);
}
